In [1]:
import numpy as np
import sys

In [2]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
#get a specific element
a[1,5]

13

In [4]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
# get a specific column
a[:,2]

array([ 3, 10])